# Generated by Django 4.1 on 2022-09-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_itempedido_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
